# Generated by Django 5.2.4 on 2025-10-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_growth_growthrecord_alter_profile_phase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sleep',
            name='phase',
            field=models.CharField(choices=[('child', 'Child'), ('adulthood', 'Adulthood'), ('menopause', 'Menopause')], default='adulthood', max_length=20),
        ),
    ]
